env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  # SolidJS用Plugin追加
  - plugin:solid/typescript
  # prettierの追加
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  # SolidJS用Plugin追加
  - solid
rules: {}
